In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

In [3]:
arr1 = np.zeros((3,4))
arr1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [5]:
np.full((4, 6), 7)

array([[7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7]])

In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
np.arange(1, 100, 9) #(Start, end, diff)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [14]:
np.linspace(1, 100, 5) #(Start, End, No. of elements)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [15]:
myarr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [11, 12, 13]])
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [18]:
#Order
myarr.shape

(4, 3)

In [19]:
#Total no. of elements
myarr.size

12

In [21]:
#Dimensions
myarr.ndim

2

In [22]:
myarr.dtype

dtype('int64')

In [23]:
myarr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [11, 12, 13]], dtype='float32')
myarr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [11., 12., 13.]], dtype=float32)

In [24]:
n = myarr.astype('float64')
n.dtype

dtype('float64')