In [1]:
import numpy as np

In [2]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [11, 12, 13]])
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [3]:
flat = arr.flatten()
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [5]:
flat[5]

np.int64(6)

In [6]:
flat[3 : 6]

array([4, 5, 6])

In [7]:
flat[ : 5]

array([1, 2, 3, 4, 5])

In [8]:
flat[5 : ]

array([ 6,  7,  8,  9, 11, 12, 13])

In [9]:
flat[ :: 2] #Print every 2nd element

array([ 1,  3,  5,  7,  9, 12])

In [10]:
b = flat[3 : 7]
b

array([4, 5, 6, 7])

In [12]:
b[0] = 5678 #Slicing creates view and not a copy
flat

array([   1,    2,    3, 5678,    5,    6,    7,    8,    9,   11,   12,
         13])

In [17]:
c = flat[7 : 13].copy() #To create copy -> original array not affected
c

array([ 8,  9, 11, 12, 13])

In [15]:
c[0] = 808
c

array([808,   9,  11,  12,  13])

In [16]:
flat

array([   1,    2,    3, 5678,    5,    6,    7,    8,    9,   11,   12,
         13])

Fancy Indexing

In [18]:
arr1 = np.array([1, 54, 23, 53, 2, 3, 34, 5, 6])
arr1[[1, 4, 6]]

array([54,  2, 34])

In [19]:
print(arr1[[1, 4, 6]])

[54  2 34]


Masking

In [20]:
mask = arr1 > 25
print(arr1[mask])

[54 53 34]


Practice

In [21]:
ar = np.array([[4, 5, 6], [7, 8, 9], [10, 11, 12]])
ar

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [23]:
ar.shape

(3, 3)

In [24]:
fl = np.array([1.1, 2.2, 3.3])
fl

array([1.1, 2.2, 3.3])

In [25]:
f = fl.astype('int64')
f

array([1, 2, 3])

In [35]:
ind = np.array([1, 2, 3, 4, 5, 6])
# even = [1, 3, 5]
even = [i for i in range(len(ind)) if ind[i] % 2 == 0]
print(ind[even])

[2 4 6]


In [36]:
f1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
f1.reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
arr2 = np.array([1, 54, 23, 53, 2, 3, 34, 5, 6, 70, 56, 30, 21, 78, 77, 99, 101])
mask1 = arr2 > 50

print(arr2[mask1])

[ 54  53  70  56  78  77  99 101]
