In [1]:
import numpy as np

In [2]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
rows = np.sum(arr, axis = 0)
cols = np.sum(arr, axis = 1)

print(f"Sum of elements in rows: {rows}")
print(f"Sum of elements in columns: {cols}")

Sum of elements in rows: [12 15 18]
Sum of elements in columns: [ 6 15 24]


In [4]:
arr[0][1]

np.int64(2)

In [5]:
arr[0, 1]

np.int64(2)

In [6]:
arr[0:2, 1:3]

array([[2, 3],
       [5, 6]])

In [7]:
arr3D = np.array([
    [[1, 2, 3], 
     [4, 5, 6]],
    
    [[7, 8, 9], 
     [10, 11, 12]]
])
arr3D

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [8]:
arr3D.shape #Depth, Rows, Coloums

(2, 2, 3)

In [9]:
arr3D[0, 1, 2] #1st Sheet, 2nd Row, 3rd Column

np.int64(6)

In [10]:
print(arr3D[:, 0, :]) #All depth, 1st row, all columns

[[1 2 3]
 [7 8 9]]


Selecting Data along Axis

In [14]:
arr3D[:, 0, :] = 0
arr3D

array([[[ 0,  0,  0],
        [ 4,  5,  6]],

       [[ 0,  0,  0],
        [10, 11, 12]]])