In [1]:
import numpy as np

In [2]:
arr = np.array([3, 5, 2, 33])

In [3]:
np.max(arr)

np.int64(33)

In [4]:
np.mean(arr)

np.float64(10.75)

In [6]:
mean = arr.mean()
print(mean)

10.75


In [7]:
np.min(arr)

np.int64(2)

In [8]:
np.sum(arr)

np.int64(43)

In [9]:
np.std(arr)

np.float64(12.891373084353738)

In [10]:
np.var(arr)

np.float64(166.1875)

In [11]:
np.prod(arr)

np.int64(990)

In [12]:
np.median(arr)

np.float64(4.0)

In [13]:
np.percentile(arr, 50)  # For the 50th percentile (median)

np.float64(4.0)

In [16]:
np.argmin(arr) #Return the index of the minimum value in an array.

np.int64(2)

In [15]:
np.argmax(arr)

np.int64(3)

In [17]:
np.corrcoef(arr1, arr2)

NameError: name 'arr1' is not defined

In [18]:
np.unique(arr)

array([ 2,  3,  5, 33])

In [19]:
np.diff(arr)

array([ 2, -3, 31])

In [20]:
np.cumsum(arr)

array([ 3,  8, 10, 43])